version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9 # installs python 3.9
    commands:
      - echo ===install cfn-lint===
      - pip install cfn-lint
      # you can add commands section to install if you want to directly input installation code forcfn-lint
      # pip install cfn-lint
      # not all resources can be installed using runtime-versions; see package documentation
    finally:
      - echo This always runs even if the installing runtime-versions fails
  pre_build:
    commands:
      - echo ===check version of python installed===
      - python3 --version
      - echo ===check cfn-lint version===
      - cfn-lint --version
    finally:
      - echo This always runs even if the command fails
  build:
    commands:
      - echo Entered the build phase...
      - echo ===check for cloudformation template===
      - ls -l
      - echo == run cfn-lint on template in file==
      - cfn-lint ec2templates.yaml
      - echo == build template artifact for next stage==
      - aws cloudformation package --template-file ec2templates.yaml --s3-bucket julytrainbucket --output-template-file CF-source-artifact.yaml
      - echo === Check if CF-source-artifact.yaml exists ===
      - ls -l CF-source-artifact.yaml

  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`


artifacts:
  files:
    - CF-source-artifact.yaml
 

  